x-common-opts: &common-opts
  volumes:
  - /etc/localtime:/etc/localtime:ro
  environment:
  - TZ=Europe/Paris

services:
  air:
    <<: *common-opts
    image: symfonymick-dev_gd-imagick-pdo_pgsql-sockets-snappy-yaml_python
    container_name: air
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - ./var/log/php-fpm:/var/log/php-fpm
      - ./var/log/supervisor:/var/log/supervisor
    restart: always
    ports:
      - 8507:80
  air-db:
    <<: *common-opts
    container_name: air-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dbair
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: air
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dbair", "-U", "air"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data-air:/var/lib/postgresql/data:rw

volumes:
  database_data-air:
