#!/bin/bash
# Vérifier si le répertoire ../base existe
if [ ! -d "../base" ]; then
    echo "Le répertoire ../base n'existe pas."
    exit 1
fi
# on copie d'office tout ce qui touche au dashboard
echo "copie d'office de dashboard templates"
rm -rf ../base/templates/dashboard
cp -r templates/dashboard ../base/templates/dashboard
echo "copie le dashboardController"
cp src/Controller/DashboardController.php ../base/src/Controller/DashboardController.php
echo "copie des assets/controllers"
rm -rf ../base/assets/controllers/*
cp  assets/controllers/* ../base/assets/controllers/. #on ne copie que les fichiers pas le dir site
mkdir ../base/assets/controllers/site

# Parcourir les fichiers du répertoire ../base
find ../base -type f -not -path "../base/.git/*" -not -path "../base/vendor/*" -not -path "../base/public/assets/*" -not -path "../base/assets/vendor/*" -not -name "compose.yaml" -not -name "importmap.php" -not -name "Caddyfile" -not -name ".env" -not -name ".env.dev" -not -name ".ignore" -not -name "compose.override.yaml" -not -name "README.md" -not -name "importmap.json" -not -path "../base/assets/styles/*" -not -name ".phpunit.result*" -not -name "composer.lock" -not -name "../base/src/Controller/DashboardController.php" -not -path "../base/templates/dashboard/*" -not -path "../base/assets/controllers/*" | while IFS= read -r file; do
    # Obtenir le chemin relatif
    rel_path=${file#../base/}
    
    # Vérifier si le fichier existe dans le répertoire courant
    if [ -f "./$rel_path" ]; then
        # Vérifier si le fichier a été modifié
        if ! cmp -s "$file" "./$rel_path"; then
            echo "Mise à jour proposée: $rel_path"
            echo "Voulez-vous mettre à jour le fichier $file avec la version actuelle ? (O/n)"
            read -r response </dev/tty  # Force la lecture depuis le terminal
            
            response=${response,,} # Mettre en minuscule
            if [[ -z "$response" || "$response" == "o" || "$response" == "y" ]]; then
                # Copier la version actuelle vers ../base
                cp "./$rel_path" "$file"
                echo "Mise à jour terminée: $rel_path"
            else
                echo "Mise à jour ignorée pour: $rel_path"
            fi
        fi
    fi
done
